name: Release Magic

on:
  release:
    types: [prereleased]

jobs: 
  deploy:
    name: Build and deploy prereleased packages 

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core    
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/filipjansson/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Clean
      run: dotnet clean

    - name: Build release
      run: dotnet build -c Release

    - name: Package project
      run: dotnet pack Magic.sln --no-build -c Release -o ./artifacts