name: Release Magic

on:
  release:
    types: [published]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout repository
    - uses: actions/checkout@v2

    # Setup .NET Core
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/filipjansson/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # Build and pack
    - name: Build solution and generate NuGet package
      run: ./package.sh

    # Push to NuGet
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./artifacts/*.nupkg --skip-duplicate